adding diksha docs hooks

diff --git a/diksha-docs/pre-push b/diksha-docs/pre-push
--- a/diksha-docs/pre-push
+++ b/diksha-docs/pre-push
@@ -10,8 +10,7 @@ prod_base_branch_name="prod-master"
 
 # The below branch is the one onto which your feature branch will we rebased. 
 # When writing code for DEV env use the branch name as dev-master and for prod use prod-master below
-custom_base_branch_name="dev-master"
-
+custom_base_branch_name="prod-master"
 git fetch origin ${custom_base_branch_name}
 
 currentBranchHash=$(git rev-parse heads/${current_branch})
@@ -24,15 +23,10 @@ echo "${currentBranchHash} ::: ${remoteMasterHash}  :::: ${commonMergeBaseHash}"
 
 # Rebase the current branch with the master branch
 [ "${rebase_required}" = "true" ] && echo "Error: Rebase is Required before pushing!! Going to rebase ${current_branch} onto ${custom_base_branch_name} " || echo "Info: Your current branch is up to date with the latest commits in ${custom_base_branch_name}"
+git rebase origin/${custom_base_branch_name}
 
-if [ "${rebase_required}" = "true" ]; then
-    git rebase origin/${custom_base_branch_name}
-    
-    # Check if the rebase was successful
-    if [ $? -ne 0 ]; then
-        echo "Error: Unable to rebase with ${custom_base_branch_name} branch. Please resolve conflicts and try again."
-        exit 1
-    fi
+# Check if the rebase was successful
+if [ $? -ne 0 ]; then
+    echo "Error: Unable to rebase with ${custom_base_branch_name} branch. Please resolve conflicts and try again."
+    exit 1
 fi
-
-
